import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import LenisProvider from "./providers/LenisProvider";
import { ViewTransitions } from "next-view-transitions";
import Footer from "@/components/footer/Footer";
import Resume from "@/components/resume/Resume";
import MaskCursor from "@/components/maskCursor/MaskCursor";


import { getCurrentUser } from "@/lib/auth.server";
import { AuthProvider } from "@/contexts/authContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const { isLoggedIn} = await getCurrentUser();

  return (
    <ViewTransitions>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <LenisProvider>
          <Navbar />
          {/* <MaskCursor /> */}
          <AuthProvider isLoggedIn={isLoggedIn}>
            {children}
          </AuthProvider>
          <Resume />
        </LenisProvider>
        
      </body>
    </html>
    </ViewTransitions>
  );
}
