import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import LenisProvider from "./providers/LenisProvider";
import { ViewTransitions } from "next-view-transitions";
import Footer from "@/components/footer/Footer";
import Resume from "@/components/resume/Resume";
import { AuthProvider } from "@/contexts/authContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Tells Safari to fill the full screen edge-to-edge and use dynamic
// viewport height so 100dvh behaves correctly on Mac/iOS Safari.
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  interactiveWidget: "resizes-content",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <LenisProvider>
          <Navbar />
          {/* <MaskCursor /> */}
          <AuthProvider>
            {children}
          </AuthProvider>
          <Resume />
        </LenisProvider>
        
      </body>
    </html>
    </ViewTransitions>
  );
}
